### ISSUE TITLE
[Feature] Parser for LG G4

### ISSUE THREAD

**Issue by asksven** [asksven/BetterBatteryStats#733]
http://forum.xda-developers.com/showpost.php?p=63275621&postcount=29565

**Comment by asksven** [comment]
anyone still wants this?

**Comment by gaich** [comment]
Of course!

**Comment by asksven** [comment]
Could you please post the header of a dumpfile here so that I have all the devices information to handle the exception on

**Comment by gaich** [comment]
===================
General Information
===================
BetterBatteryStats version: 2.2.0.0B4
Creation Date: 2016-01-04 09:03:54
Statistic Type: Custom to Current
Since 9 h 37 m 13 s 
VERSION.RELEASE: 5.1
BRAND: lge
DEVICE: p1
MANUFACTURER: LGE
MODEL: LG-H815
OS.VERSION: 3.10.49-g486a0bf
BOOTLOADER: unknown
HARDWARE: p1
FINGERPRINT: lge/p1_global_com/p1:5.1/LMY47D/1522918234efe:user/release-keys
ID: LMY47D
TAGS: release-keys
USER: jenkins
PRODUCT: p1_global_com
RADIO: MPSS.BO.2.5.c3-00075-M8992FAAAANAZM-1.24249.2.24414.5
Root perms: true
SELinux Policy: Enforcing
BATTERY_STATS permission granted: true
XPosed BATTERY_STATS module enabled: false
============
Battery Info
