### ISSUE TITLE
Use static analysis technique to scan wakelock NoSleep Bug?

### ISSUE THREAD

**Issue by GeekMin** [asksven/BetterBatteryStats#785]
hmmm, recently I meet with wakelock problems...
After I refer to this two papers, Totally, the paper tells me that:
[
1. http://mesl.ucsd.edu/yuvraj/docs/Vekris_HotPower12_TowardsVerifyingApps.pdf
2. https://software.intel.com/en-us/android/articles/wakelocks-detect-no-sleep-issues-in-android-applications
]
we have two directions to deal with this problem..
1. static analysis(Complete, but introduce more false-positives)

2. dynamic analysis(Partial, but introduce more false-negatives)
(**like BetterBatteryStats**)
Maybe I misundertand this problem..

So If I want to combine these two methods,
Is there a ready-made static analysis tool to detect this problem~?
If yes, where can I get it~?

**Comment by asksven** [comment]
From my experience no-sleep is more often related to something preventing the power cycle, rather than a wakelock. Anyway I would like to understand what you mean with false negatives. Do you mean there are wakelocks  of registered by the kernel? Or that no-sleep can can causes else than wakelocks? I would agree on the latter: a driver  or properly releasing an irq would cause a  no-sleep issue without wakelocka

**Comment by GeekMin** [comment]
hmmm, compared with Dynamic-checking, why false negatives happens is that:
sometimes, the lock is not normally released because some exceptions happened between 
acquire and release.. Totally, I think just using dynamic-checking, you can not be sure that
you have 100% coverage about the code-execution-path..during the dynamic-checking-test..
That's my thinking

**Comment by asksven** [comment]
neither a bug nor a feature request. closing
